version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/eshop
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - mysql/mysql.env
    volumes:
      - db:/var/lib/mysql
    user: "1000:1000"
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www/eshop

  composer:
    build:
      context: .
      dockerfile: php/composer.Dockerfile
    volumes:
      - ./app:/var/www/eshop
    user: "1000:1000"
  artisan:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www/eshop
    entrypoint: ["php", "/var/www/eshop/artisan"]
    user: "1000:1000"
  npm:
    image: node:18.16.0-alpine
    working_dir: /var/www/eshop
    entrypoint: ["npm"]
    volumes:
      - ./app:/var/www/eshop
    user: "1000:1000"

volumes:
  db:
